### ISSUE TITLE
Needs more hints for the less experienced

### ISSUE THREAD

**Issue by fpp-gh** [jwergieluk/periscope#1]
Hi, 
Periscope is an impressive, fluid and good-looking dashboard demo (and in pygame, no less ! :).

However, the code is very tight and terse, using advanced Python3 syntax, and exactly zero comment inside.

I think this is a shame, as this example could really be of use to other python users looking for such a component.

I am a longtime python2 (non-pro) coder, and I'm still struggling to wrap my brain around this code.

How about making your demo more approachable, with a heavily-commented version, and maybe some real-life use cases ?

TIA,
fp

**Comment by jwergieluk** [comment]
Hey, this package was developed for a blog post which you can find here: https://www.wergieluk.com/posts/periscope/
The post explains the basic ideas behind this dashboard library. If you want more info, I would suggest consulting (excellent) pygame documentation or maybe have a look at their demos. Julian

**Comment by fpp-gh** [comment]
Hi Julian,
Thanks for the quick reply and sorry for the (almost) useless issue !
I guess my search took me directly to the Github page (that doesn't seem to link to your blog), so I didn't see your post there... but it's exactly what I was looking for :-)
I'll close this issue now and go read it until I really get it :-)
Best,
fp

**Comment by fpp-gh** [comment]
Issue made redundant by blog post in Julian's answer above.

**Comment by jwergieluk** [comment]
Np! I'll make sure the link to the post is in readme too. Thanks!
